
class TaskNotFoundError(Exception):
    pass

class ExistingTaskError(Exception):
    pass
